apiVersion: v1
kind: Namespace
metadata:
  name: gitops-mas-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-mas-monitor-operator-group
  namespace: gitops-mas-monitor
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-mas-monitor
---
